### ISSUE TITLE
Add word for Clarity, Section 4.2.2

### ISSUE THREAD

**Issue by sgornick** [coinop-logan/ZimDai#1]
In 4.2.2 (Early Agent Liquidity Without Exchanges):

"This allows agents to essentially turn local currency into Dai"

Since agents generally serve customers, this was confusing to me.  I had to re-read it a couple times to understand that it was describing the agent being able to use a remittance trade as a method to convert the agent's local currency into Dai  (by paying out to the remittance recipient the cash, but receiving the DAI from the remittance sender).

Maybe just adding a single word makes it more clear ..."their"

"This allows agents to essentially turn _their_ local currency into Dai"

or even

"This allows agents to essentially turn _their own_ local currency into Dai"

**Comment by coinop-logan** [comment]
@sgornick I've addressed this and the other issues you've made, after happening upon their existence recently. Thanks for these!
